---
title: "Data Management for Social Scientists"
format: html
description: 'A short description of the book "Data Management for Social Scientists" by Nils B. Weidmann'
author: David Schoch
institute: GESIS - Leibniz Institute for the Social Sciences
---

# Overview

The book "Data Management for Social Scientists" by Nils B. Weidmann addresses the need for improved data processing and management in empirical social science research. It emphasizes the importance of properly preparing data for analysis, which is often overlooked in social science training. The book aims to bridge this gap by providing guidance on data processing and management using various tools and software packages.

Data processing involves tasks such as cleaning, recoding, and combining data to create analysis-ready datasets. A properly documented (automated) data processing pipeline can enhance transparency and replicability of a research pipeline and adds convenience for researchers. To achieve this, the book challenges some conventional practices, such as using spreadsheets for data management, and highlights the benefits of specialized software for efficient data processing.

The book is divided into five parts. The first part includes the introduction, discussing the role of data preparation and management, as well as the software setup. The second part covers data processing with files, including an overview of file-based data storage and data management using spreadsheet software and R. The third part focuses on specialized systems, such as databases, explaining relational databases and their technical features. The fourth part addresses specialized data types like spatial, text, and network data, discussing their processing with R and database systems. The fifth part concludes with recommendations for collaborative data projects and data publication. The book aims to provide an overview of different tools and approaches for data management.


The book is available as open access

:::{style="text-align:center"}
<https://doi.org/10.1017/9781108990424>
:::

# About the author

Nils Weidman is a Professor of Political Science and head of the "Communication, Networks and Contention" Research Group at the University of Konstanz, Germany. He held research fellowships at the Centre for the Study of Civil War, Peace Research Institute Oslo (2011-12), the Jackson Institute, Yale University (2010-11), and the Woodrow Wilson School, Princeton University (2009-10). He received a M.Sc. in Computer Science from the University of Freiburg (Germany) in 2003, a M.A. in Comparative and International Studies from ETH Zurich (Switzerland) in 2008, and a Ph.D. in Political Science from ETH Zurich in 2009.